---
title: "Grüngut"
author: "Levi Fuchs"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## Auswertung Grüngut

Für die Energiestatistik werden auch Angaben zu Grüngut ausgewertet<br> Die Grüngut-Daten liegen als Excel-Daten vor und können mit R eingelesen, umgeformt und ausgewertet werden.

# Inputdaten

```{r}
#| label: load-packages
#| include: false

rm(list = ls())

# Benötigte Pakete
library(readxl)
#library(dplyr)
#library(stringr)
library(tidyverse)
#library(sf)

current_year <- as.integer(format(Sys.Date(), "%Y"))
```

```{r}
#| label: load-input-data
#| include: false

gruengut_orig <- read_excel("K:/BD-AWEL-Ef/Elektrizitätswirtschaft/Administration/Praktikum/Levi_Fuchs/Projekte/Energiestatistik_neu/R_Project/Grüngut/Energiezahlen 20 Jahre.xlsx", col_names = F)

gruengut_input <- gruengut_orig %>%
  {
    # Suche nach einer Zeile, in der irgendwo "gwh" vorkommt (case-insensitive)
    start <- which(apply(., 1, function(row) any(grepl("gwh", row, ignore.case = TRUE))))[1]
    . <- slice(., start:n())
    colnames(.) <- .[1, ]
    slice(., -1)
  }


gruengut_final <- gruengut_input %>%
  rename(kategorie = `in GWh`) %>%  # Spalte umbenennen für Klarheit
  pivot_longer(
    cols = -kategorie,              # Alle Spalten außer "kategorie" ins Long-Format bringen
    names_to = "jahr",              # Neue Spalte für Jahre
    values_to = "wert"              # Neue Spalte für die Werte
  ) %>%
  mutate(jahr = as.integer(jahr)) %>%   # Jahr als echte Zahl (optional, falls nötig)
  pivot_wider(
    names_from = kategorie,   # Jede Kategorie wird eine eigene Spalte
    values_from = wert        # Die Werte kommen in diese Spalten
  ) %>%
  mutate(
    gruengut_abwaerme_mwh_zh = `Wärme verkauft` * 1000,
    gruengut_strom_mwh_zh = `Strom netto verkauft` * 1000,
    gruengut_biogas_mwh_zh = `Biogas in Erdgasnetz` * 1000,
    gruengut_holz_mwh_zh = `thermisch genutzt Holz und Siebüberlauf` * 1000,
  ) %>%
  select(jahr, gruengut_abwaerme_mwh_zh, gruengut_strom_mwh_zh, gruengut_biogas_mwh_zh, gruengut_holz_mwh_zh)
```

# Export

```{r}

write.csv(gruengut_final, file.path(file.path(dirname(dirname(rstudioapi::getActiveDocumentContext()$path)), "data", "output"), "gruengut.csv"), row.names = FALSE)
```
